spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Application4/common-config
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9494

